name: Release to Server
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup GO
      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Download Modules
      - name: Download Modules
        run: go mod download

      # Build
      - name: Build Project
        run: go build -ldflags="-s -w" -trimpath -o ./server ./main.go
        
      # Upload
      - name: Upload to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./new_server
          target: /srv/ncth-scfests-api

      # Replacing API Server
      - name: Replacing API Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /srv/ncth-scfests-api/
            sh ./stop.sh
            rm -f ./server
            mv ./new_server ./server
            sh ./start.sh
